name: Grelmin CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run Gradle build
      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      # Run PMD
#      - name: Run PMD
#        run: ./gradlew pmdMain --no-daemon

      # Run Checkstyle
#      - name: Run Checkstyle
#        run: ./gradlew checkstyleMain --no-daemon

      # Upload test results (optional)
#      - name: Archive test results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-results
#          path: build/reports/tests/test
